/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameoflife;

import static gameoflife.GameOfLife.*;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author Ethan
 */
public class UtilFrame extends javax.swing.JFrame {

    /**
     * Creates new form UtilFrame
     */
    public UtilFrame() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Load");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Open");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Shuffle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //RESET
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean btmp = awake;
        awake = false;
        while(!rdy2draw)
            try{Thread.sleep(1);}catch(Exception e){}
        for(int i = 0; i < cells.length; i++)
            for(int j = 0; j < cells[0].length;j++)
                cells[i][j] = 0;
        active.clear();
        awake = btmp;
    }//GEN-LAST:event_jButton1ActionPerformed

    //OPEN
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser jfc = new JFileChooser(System.getProperty("user.dir"));
        int stat = jfc.showOpenDialog(frame);
        if(stat != JFileChooser.APPROVE_OPTION)
            return;
        jTextField1.setText(jfc.getSelectedFile().getPath());
    }//GEN-LAST:event_jButton4ActionPerformed

    //LOAD
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean btmp = awake;
        awake = false;
        while(!rdy2draw)
            try{Thread.sleep(1);}catch(Exception e){}
        //LOAD HERE
        try{
            File f = new File(jTextField1.getText());
            DataInputStream dis = new DataInputStream(new BufferedInputStream(new FileInputStream(f)));
            NUMX = dis.readInt();
            NUMY = dis.readInt();
            db = new BufferedImage(NUMX, NUMY, BufferedImage.TYPE_INT_RGB);
            active.clear();
            cells = new byte[db.getWidth()][db.getHeight()];
            System.gc();
            
            int count = 0;
            while(count < NUMX*NUMY){
                int amt = dis.readInt();
                byte val = dis.readByte();
                for(int i = 0; i < amt; i++){
                    cells[count%NUMX][count/NUMX] = val;
                    if(val > 0)
                        active.add(new Point(count%NUMX,count/NUMX));
                    count++;
                }
            }
            
            dis.close();
        }catch(Exception e){}
        awake = btmp;
    }//GEN-LAST:event_jButton3ActionPerformed

    //SAVE
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean btmp = awake;
        awake = false;
        while(!rdy2draw)
            try{Thread.sleep(1);}catch(Exception e){}
        //SAVE HERE
        try{
            File f = new File(jTextField1.getText());
            DataOutputStream dos = new DataOutputStream(new BufferedOutputStream(new FileOutputStream(f)));
            dos.writeInt(NUMX);
            dos.writeInt(NUMY);
            byte prev = 0;
            int strk = 0;
            for(int i = 0; i < cells.length; i++)
                for(int j = 0; j < cells[0].length; j++){
                    if(cells[j][i] != prev && strk > 0){
                        dos.writeInt(strk);
                        dos.writeByte(prev);
                        prev = cells[j][i];
                        strk = 1;
                    }
                    else{
                        strk++;
                    }
                }
            dos.writeInt(strk);
            dos.writeByte(prev);
            dos.close();
        }catch(Exception e){}

        awake = btmp;
    }//GEN-LAST:event_jButton2ActionPerformed

    //SHUFFLE
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boolean btmp = awake;
        awake = false;
        while(!rdy2draw)
            try{Thread.sleep(1);}catch(Exception e){}
        active.clear();
        for(int i = 0; i < cells.length; i++)
            for(int j = 0; j < cells[0].length;j++){
                byte tmp = Math.random() < 0.05 ? (byte)1 : (byte)0;
                if(tmp > 0)
                    active.add(new Point(i,j));
                cells[i][j] = tmp;
            }
            awake = btmp;
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
